services:
  frontend:
    image: ghcr.io/rvoltz/quotefy-front-app:deb7c1b1165f2da01d62cdfe7d3795e85be04945
    env_file: [front.env]
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - target: 80
        published: 62080
        protocol: tcp
        mode: host
    networks:
      - quotefy-back-hml_quotefy-net

networks:
  quotefy-back-hml_quotefy-net:
    external: true
